### ISSUE TITLE
Feature Request = Make Ponch Polite again

### ISSUE THREAD

**Issue by lespinalrivera** [Surreycodecamp/surreycodecamp-hubot#4]
This feature request is Beginners friendly:

We need a more Canadian Ponch, Everytime someone says "Thank you" he should reply something...

That something can be "You are welcome @{user}" or something equally polite :+1:

**Comment by coulterpeterson** [comment]
I'll try to figure out some Ponch code today :)

**Comment by coulterpeterson** [comment]
Pull request submitted - thanks for posting the issue

**Comment by lespinalrivera** [comment]
Ponch is polite again! thank you!
